name: Update SRCINFO

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '**/PKGBUILD'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pkgbuilds: ${{ steps.matrix.outputs.pkgbuilds }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Find updated packages and construct matrix
        id: matrix
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          dirs=$(git diff --name-only origin/main HEAD "*PKGBUILD" | xargs dirname)
          # Convert dirs that have been changed to a JSON array
          echo "pkgbuilds=$(printf '["%s"]' "$(echo "$dirs" | sed ':a;N;$!ba;s/\n/","/g')")" >> $GITHUB_OUTPUT

  update:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      max-parallel: 1 # Hopefully we can remove this in the future
      matrix:
        pkgbuild: ${{fromJSON(needs.setup.outputs.pkgbuilds)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Validate packages
        if: ${{ matrix.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          action: 'updpkgsums'
          pkgname: ${{ matrix.pkgbuild }}

      - name: Commit
        if: ${{ matrix.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          file_pattern: '*/PKGBUILD */.SRCINFO'
          commit_user_name: Hammy # defaults to "github-actions[bot]"
          commit_user_email: <58985301+sgoudham@users.noreply.github.com> # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
